### PR TITLE
Added clustering_slicewise.py; clarified comments

### PR DESCRIPTION
**Pull request by jcohenadad**
To test:
- download atlas: https://osf.io/g7kx8/
- install ANTs
- edit `param.py` set the correct paths
- run: `python register_slicewise.py`
- run: `python clustering_slicewise.py`

### CODE REVIEW

**Comment by alexfoias** [comment]
Here are some examples:
### Paxinos left side
clustering_results_ncluster8_C1
concatenated_image-C1
### Paxinos right side
clustering_results_ncluster8_C1
concatenated_image-C1

**Comment by alexfoias** [comment]
@HarrisNami Could you please validate that the description for the 4th dimension is right ?https://github.com/neuropoly/tract-clustering/pull/4/files#diff-80b7659c487dcdf6ffee3d3ddf26bfbdR60

**Comment by HarrisNami** [comment]
Yes that looks right to me. It's the white matter mask of the various
tracts of the paxinos atlas.

**Comment by alexfoias** [comment]
Here is an example of output. I think the algorithm for matching the colours in **get_best_matching_color_with_paxinos** clustering_results_ncluster8_C1

Some mapping was done manually for the colours https://github.com/neuropoly/tract-clustering/blob/master/scripts/params.py#L64

I would need some help in understanding the algorithm.

**Comment by HarrisNami** [comment]
Alright, what will you need help with? I believe Julien had done most of
the colour matching algorithm but I can try and help. The matching does
seem to be off a bit though, like the green at the bottom should definitely
be blue and so on.

**Comment by alexfoias** [comment]
Results from https://github.com/neuropoly/tract-clustering/pull/4/commits/301a483dd1a96062fe42c71646da7d662b8dd499
### ncluster8_C1
clustering_results_ncluster8_C1
### ncluster8_C2
clustering_results_ncluster8_C2
### ncluster8_C3
clustering_results_ncluster8_C3

**Comment by jcohenadad** [comment]
i think you nailed it @alexfoias 🥇

**Pull request merged**
